name: deploy lambda

on:
    push:
      branches:
        - main
      paths-ignore:
        - '**.md'
    workflow_dispatch:


jobs:   
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Setup Go 1.21.x
              uses: actions/setup-go@v4
              with:
                go-version: '1.21.x'
                
            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v3

            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ secrets.AWS_REGION }}

            - name: Build Lambda
              run: |
                GOOS=linux GOARCH=amd64 go build -tags lambda.norpc -o bootstrap main.go
                
            - name: Zip Lambda
              run: |
                zip bootstrap.zip bootstrap

            - name: Terraform
              run: |
                cd infrastructure
                terraform init
                terraform refresh
                terraform plan -out=tfplan
                terraform apply -auto-approve

            - name: Deploy to AWS Lambda
              uses: appleboy/lambda-action@v0.0.2
              with:
                aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws_region: us-east-1 
                function_name: rust-lambda
                zip_file: bootstrap.zip